const LEARNING_DATA = {
  books: [
    {id:1,title:'The Feynman Lectures on Physics',author:'Richard Feynman',category:'Physics',url:'https://www.feynmanlectures.caltech.edu/',desc:'Complete physics lectures by Nobel laureate - FREE online',chapters:52},
    {id:2,title:'Deep Learning Book',author:'Ian Goodfellow',category:'AI/ML',url:'https://www.deeplearningbook.org/',desc:'Comprehensive deep learning textbook - FREE online',chapters:20},
    {id:3,title:'Automate the Boring Stuff with Python',author:'Al Sweigart',category:'Programming',url:'https://automatetheboringstuff.com/',desc:'Learn Python programming - FREE online',chapters:20},
    {id:4,title:'Eloquent JavaScript',author:'Marijn Haverbeke',category:'Programming',url:'https://eloquentjavascript.net/',desc:'Modern JavaScript programming - FREE online',chapters:22},
    {id:5,title:'Introduction to Algorithms (MIT)',author:'CLRS',category:'Computer Science',url:'https://ocw.mit.edu/courses/6-006-introduction-to-algorithms-fall-2011/',desc:'MIT algorithms course - FREE',chapters:35},
    {id:6,title:'Neural Networks and Deep Learning',author:'Michael Nielsen',category:'AI/ML',url:'http://neuralnetworksanddeeplearning.com/',desc:'Visual deep learning book - FREE online',chapters:6},
    {id:7,title:'Think Python',author:'Allen Downey',category:'Programming',url:'https://greenteapress.com/wp/think-python-2e/',desc:'Introduction to Python - FREE PDF',chapters:21},
    {id:8,title:'You Don\'t Know JS',author:'Kyle Simpson',category:'Programming',url:'https://github.com/getify/You-Dont-Know-JS',desc:'Deep JavaScript series - FREE on GitHub',chapters:6},
    {id:9,title:'The Nature of Code',author:'Daniel Shiffman',category:'Programming',url:'https://natureofcode.com/',desc:'Simulating natural systems - FREE online',chapters:10},
    {id:10,title:'Mathematics for Machine Learning',author:'Deisenroth et al',category:'Mathematics',url:'https://mml-book.github.io/',desc:'Math foundations for ML - FREE PDF',chapters:12}
  ],
  videos: [
    {id:1,title:'Python Full Course',channel:'freeCodeCamp',category:'Programming',videoId:'rfscVS0vtbw',duration:'4:26:52',desc:'Complete Python tutorial for beginners'},
    {id:2,title:'JavaScript Full Course',channel:'freeCodeCamp',category:'Programming',videoId:'PkZNo7MFNFg',duration:'3:26:42',desc:'Learn JavaScript from scratch'},
    {id:3,title:'Machine Learning Course',channel:'Stanford Online',category:'AI/ML',videoId:'jGwO_UgTS7I',duration:'2:18:27',desc:'Andrew Ng ML course introduction'},
    {id:4,title:'Neural Networks Explained',channel:'3Blue1Brown',category:'AI/ML',videoId:'aircAruvnKk',duration:'19:13',desc:'Visual introduction to neural networks'},
    {id:5,title:'Quantum Mechanics',channel:'MIT OpenCourseWare',category:'Physics',videoId:'lZ3bPUKo5zc',duration:'1:24:33',desc:'MIT quantum mechanics lecture'},
    {id:6,title:'Data Structures Easy to Advanced',channel:'freeCodeCamp',category:'Computer Science',videoId:'RBSGKlAvoiM',duration:'8:18:00',desc:'Complete data structures course'},
    {id:7,title:'Algorithms Course',channel:'freeCodeCamp',category:'Computer Science',videoId:'8hly31xKli0',duration:'5:00:00',desc:'Graph algorithms and more'},
    {id:8,title:'Deep Learning Specialization',channel:'deeplearning.ai',category:'AI/ML',videoId:'CS4cs9xVecg',duration:'1:15:20',desc:'Deep learning fundamentals'},
    {id:9,title:'Linear Algebra',channel:'3Blue1Brown',category:'Mathematics',videoId:'fNk_zzaMoSs',duration:'12:09',desc:'Essence of linear algebra'},
    {id:10,title:'Calculus',channel:'3Blue1Brown',category:'Mathematics',videoId:'WUvTyaaNkzM',duration:'3:27:46',desc:'Essence of calculus'},
    {id:11,title:'React Full Course',channel:'freeCodeCamp',category:'Web Development',videoId:'bMknfKXIFA8',duration:'11:55:27',desc:'Complete React tutorial'},
    {id:12,title:'Node.js Full Course',channel:'freeCodeCamp',category:'Web Development',videoId:'Oe421EPjeBE',duration:'8:16:48',desc:'Backend with Node.js'},
    {id:13,title:'SQL Full Course',channel:'freeCodeCamp',category:'Database',videoId:'HXV3zeQKqGY',duration:'4:20:46',desc:'Complete SQL tutorial'},
    {id:14,title:'Git and GitHub',channel:'freeCodeCamp',category:'Tools',videoId:'RGOj5yH7evk',duration:'1:08:41',desc:'Version control tutorial'},
    {id:15,title:'Docker Tutorial',channel:'TechWorld with Nana',category:'DevOps',videoId:'3c-iBn73dDE',duration:'3:10:23',desc:'Complete Docker course'},
    {id:16,title:'Kubernetes Course',channel:'freeCodeCamp',category:'DevOps',videoId:'X48VuDVv0do',duration:'3:49:39',desc:'K8s for beginners'},
    {id:17,title:'AWS Certified Cloud Practitioner',channel:'freeCodeCamp',category:'Cloud',videoId:'3hLmDS179YE',duration:'13:56:31',desc:'AWS fundamentals'},
    {id:18,title:'Cybersecurity Full Course',channel:'freeCodeCamp',category:'Security',videoId:'U_P23SqJaDc',duration:'10:47:07',desc:'Security fundamentals'},
    {id:19,title:'Blockchain Full Course',channel:'freeCodeCamp',category:'Blockchain',videoId:'gyMwXuJrbJQ',duration:'16:54:05',desc:'Blockchain development'},
    {id:20,title:'TensorFlow 2.0',channel:'freeCodeCamp',category:'AI/ML',videoId:'tPYj3fFJGjk',duration:'7:00:00',desc:'Deep learning with TensorFlow'},
    {id:21,title:'PyTorch Course',channel:'freeCodeCamp',category:'AI/ML',videoId:'V_xro1bcAuA',duration:'25:38:24',desc:'Deep learning with PyTorch'},
    {id:22,title:'Computer Vision',channel:'freeCodeCamp',category:'AI/ML',videoId:'01sAkU_NvOY',duration:'3:43:17',desc:'OpenCV Python tutorial'},
    {id:23,title:'Natural Language Processing',channel:'freeCodeCamp',category:'AI/ML',videoId:'fNxaJsNG3-s',duration:'12:24:09',desc:'NLP with Python'},
    {id:24,title:'C++ Full Course',channel:'freeCodeCamp',category:'Programming',videoId:'vLnPwxZdW4Y',duration:'31:14:44',desc:'Complete C++ tutorial'},
    {id:25,title:'Java Full Course',channel:'freeCodeCamp',category:'Programming',videoId:'grEKMHGYyns',duration:'9:18:36',desc:'Learn Java programming'},
    {id:26,title:'Go Programming',channel:'freeCodeCamp',category:'Programming',videoId:'YS4e4q9oBaU',duration:'6:52:27',desc:'Golang full course'},
    {id:27,title:'Rust Programming',channel:'freeCodeCamp',category:'Programming',videoId:'BpPEoZW5IiY',duration:'13:07:00',desc:'Learn Rust from scratch'},
    {id:28,title:'Flutter Course',channel:'freeCodeCamp',category:'Mobile Dev',videoId:'VPvVD8t02U8',duration:'37:27:06',desc:'Mobile app development'},
    {id:29,title:'Unity Game Development',channel:'freeCodeCamp',category:'Game Dev',videoId:'gB1F9G0JXOo',duration:'7:31:47',desc:'Create games with Unity'},
    {id:30,title:'Ethical Hacking',channel:'freeCodeCamp',category:'Security',videoId:'3Kq1MIfTWCE',duration:'15:49:52',desc:'Penetration testing course'}
  ],
  challenges: [
    // Python Challenges (30)
    {id:1,title:'Hello World',category:'Python',difficulty:'Easy',desc:'Write a function that returns "Hello, World!"',language:'python',testCases:[{input:'',output:'Hello, World!'}],hint:'Use return statement',starter:'def hello_world():\n    # Your code here\n    pass'},
    {id:2,title:'Sum Two Numbers',category:'Python',difficulty:'Easy',desc:'Write a function that takes two numbers and returns their sum',language:'python',testCases:[{input:'5, 3',output:'8'},{input:'10, 20',output:'30'}],hint:'Use + operator',starter:'def sum_numbers(a, b):\n    # Your code here\n    pass'},
    {id:3,title:'Reverse String',category:'Python',difficulty:'Easy',desc:'Reverse a given string',language:'python',testCases:[{input:'"hello"',output:'"olleh"'},{input:'"python"',output:'"nohtyp"'}],hint:'Use slicing [::-1]',starter:'def reverse_string(s):\n    # Your code here\n    pass'},
    {id:4,title:'Palindrome Check',category:'Python',difficulty:'Easy',desc:'Check if a string is a palindrome',language:'python',testCases:[{input:'"racecar"',output:'True'},{input:'"hello"',output:'False'}],hint:'Compare string with its reverse',starter:'def is_palindrome(s):\n    # Your code here\n    pass'},
    {id:5,title:'Factorial',category:'Python',difficulty:'Medium',desc:'Calculate factorial of a number',language:'python',testCases:[{input:'5',output:'120'},{input:'0',output:'1'}],hint:'Use recursion or loop',starter:'def factorial(n):\n    # Your code here\n    pass'},
    {id:6,title:'Fibonacci',category:'Python',difficulty:'Medium',desc:'Generate nth Fibonacci number',language:'python',testCases:[{input:'7',output:'13'},{input:'10',output:'55'}],hint:'Use recursion or dynamic programming',starter:'def fibonacci(n):\n    # Your code here\n    pass'},
    {id:7,title:'Prime Check',category:'Python',difficulty:'Medium',desc:'Check if a number is prime',language:'python',testCases:[{input:'17',output:'True'},{input:'20',output:'False'}],hint:'Check divisibility up to sqrt(n)',starter:'def is_prime(n):\n    # Your code here\n    pass'},
    {id:8,title:'Binary Search',category:'Python',difficulty:'Medium',desc:'Implement binary search algorithm',language:'python',testCases:[{input:'[1,2,3,4,5], 3',output:'2'},{input:'[1,3,5,7,9], 7',output:'3'}],hint:'Use divide and conquer',starter:'def binary_search(arr, target):\n    # Your code here\n    pass'},
    {id:9,title:'Merge Sort',category:'Python',difficulty:'Hard',desc:'Implement merge sort algorithm',language:'python',testCases:[{input:'[5,2,8,1,9]',output:'[1,2,5,8,9]'}],hint:'Divide, sort, merge',starter:'def merge_sort(arr):\n    # Your code here\n    pass'},
    {id:10,title:'Two Sum',category:'Python',difficulty:'Medium',desc:'Find two numbers that add up to target',language:'python',testCases:[{input:'[2,7,11,15], 9',output:'[0,1]'}],hint:'Use hash map',starter:'def two_sum(nums, target):\n    # Your code here\n    pass'},
    {id:11,title:'Valid Parentheses',category:'Python',difficulty:'Medium',desc:'Check if parentheses are balanced',language:'python',testCases:[{input:'"()"',output:'True'},{input:'"([)]"',output:'False'}],hint:'Use stack',starter:'def is_valid(s):\n    # Your code here\n    pass'},
    {id:12,title:'Longest Substring',category:'Python',difficulty:'Hard',desc:'Find longest substring without repeating characters',language:'python',testCases:[{input:'"abcabcbb"',output:'3'},{input:'"bbbbb"',output:'1'}],hint:'Use sliding window',starter:'def length_of_longest_substring(s):\n    # Your code here\n    pass'},
    {id:13,title:'Matrix Transpose',category:'Python',difficulty:'Easy',desc:'Transpose a matrix',language:'python',testCases:[{input:'[[1,2],[3,4]]',output:'[[1,3],[2,4]]'}],hint:'Swap rows and columns',starter:'def transpose(matrix):\n    # Your code here\n    pass'},
    {id:14,title:'Find Duplicates',category:'Python',difficulty:'Medium',desc:'Find all duplicates in array',language:'python',testCases:[{input:'[1,2,3,2,4,3]',output:'[2,3]'}],hint:'Use set or hash map',starter:'def find_duplicates(arr):\n    # Your code here\n    pass'},
    {id:15,title:'Anagram Check',category:'Python',difficulty:'Easy',desc:'Check if two strings are anagrams',language:'python',testCases:[{input:'"listen", "silent"',output:'True'}],hint:'Sort or count characters',starter:'def is_anagram(s1, s2):\n    # Your code here\n    pass'},
    {id:16,title:'Max Subarray Sum',category:'Python',difficulty:'Hard',desc:'Find maximum sum of contiguous subarray',language:'python',testCases:[{input:'[-2,1,-3,4,-1,2,1,-5,4]',output:'6'}],hint:'Use Kadane\'s algorithm',starter:'def max_subarray(arr):\n    # Your code here\n    pass'},
    {id:17,title:'Rotate Array',category:'Python',difficulty:'Medium',desc:'Rotate array by k positions',language:'python',testCases:[{input:'[1,2,3,4,5], 2',output:'[4,5,1,2,3]'}],hint:'Reverse subarrays',starter:'def rotate(arr, k):\n    # Your code here\n    pass'},
    {id:18,title:'Missing Number',category:'Python',difficulty:'Easy',desc:'Find missing number in array 0 to n',language:'python',testCases:[{input:'[0,1,3]',output:'2'}],hint:'Use sum formula',starter:'def missing_number(arr):\n    # Your code here\n    pass'},
    {id:19,title:'Climbing Stairs',category:'Python',difficulty:'Medium',desc:'Count ways to climb n stairs (1 or 2 steps)',language:'python',testCases:[{input:'3',output:'3'},{input:'5',output:'8'}],hint:'Fibonacci pattern',starter:'def climb_stairs(n):\n    # Your code here\n    pass'},
    {id:20,title:'Coin Change',category:'Python',difficulty:'Hard',desc:'Minimum coins needed for amount',language:'python',testCases:[{input:'[1,2,5], 11',output:'3'}],hint:'Dynamic programming',starter:'def coin_change(coins, amount):\n    # Your code here\n    pass'},
    {id:21,title:'Linked List Reverse',category:'Python',difficulty:'Medium',desc:'Reverse a linked list',language:'python',testCases:[{input:'1->2->3->4',output:'4->3->2->1'}],hint:'Use three pointers',starter:'def reverse_list(head):\n    # Your code here\n    pass'},
    {id:22,title:'Binary Tree Height',category:'Python',difficulty:'Medium',desc:'Find height of binary tree',language:'python',testCases:[{input:'Tree with 3 levels',output:'3'}],hint:'Use recursion',starter:'def tree_height(root):\n    # Your code here\n    pass'},
    {id:23,title:'Level Order Traversal',category:'Python',difficulty:'Medium',desc:'Print tree level by level',language:'python',testCases:[{input:'Binary tree',output:'[[3],[9,20],[15,7]]'}],hint:'Use queue (BFS)',starter:'def level_order(root):\n    # Your code here\n    pass'},
    {id:24,title:'Graph DFS',category:'Python',difficulty:'Medium',desc:'Implement depth-first search',language:'python',testCases:[{input:'Graph adjacency list',output:'DFS traversal'}],hint:'Use stack or recursion',starter:'def dfs(graph, start):\n    # Your code here\n    pass'},
    {id:25,title:'Graph BFS',category:'Python',difficulty:'Medium',desc:'Implement breadth-first search',language:'python',testCases:[{input:'Graph adjacency list',output:'BFS traversal'}],hint:'Use queue',starter:'def bfs(graph, start):\n    # Your code here\n    pass'},
    {id:26,title:'Dijkstra Algorithm',category:'Python',difficulty:'Hard',desc:'Find shortest path in weighted graph',language:'python',testCases:[{input:'Weighted graph',output:'Shortest distances'}],hint:'Use priority queue',starter:'def dijkstra(graph, start):\n    # Your code here\n    pass'},
    {id:27,title:'LRU Cache',category:'Python',difficulty:'Hard',desc:'Implement LRU cache',language:'python',testCases:[{input:'Operations',output:'Expected results'}],hint:'Use OrderedDict or doubly linked list',starter:'class LRUCache:\n    def __init__(self, capacity):\n        pass'},
    {id:28,title:'Trie Implementation',category:'Python',difficulty:'Hard',desc:'Implement prefix tree',language:'python',testCases:[{input:'Insert/search words',output:'True/False'}],hint:'Use nested dictionaries',starter:'class Trie:\n    def __init__(self):\n        pass'},
    {id:29,title:'Serialize Binary Tree',category:'Python',difficulty:'Hard',desc:'Serialize and deserialize binary tree',language:'python',testCases:[{input:'Tree',output:'String representation'}],hint:'Use preorder traversal',starter:'def serialize(root):\n    # Your code here\n    pass'},
    {id:30,title:'Word Ladder',category:'Python',difficulty:'Hard',desc:'Find shortest transformation sequence',language:'python',testCases:[{input:'"hit", "cog", wordList',output:'5'}],hint:'Use BFS',starter:'def ladder_length(begin, end, word_list):\n    # Your code here\n    pass'},
    
    // JavaScript Challenges (30)
    {id:31,title:'Array Map',category:'JavaScript',difficulty:'Easy',desc:'Implement Array.map() from scratch',language:'javascript',testCases:[{input:'[1,2,3], x => x*2',output:'[2,4,6]'}],hint:'Use for loop',starter:'function map(arr, fn) {\n    // Your code here\n}'},
    {id:32,title:'Array Filter',category:'JavaScript',difficulty:'Easy',desc:'Implement Array.filter() from scratch',language:'javascript',testCases:[{input:'[1,2,3,4], x => x>2',output:'[3,4]'}],hint:'Check condition',starter:'function filter(arr, fn) {\n    // Your code here\n}'},
    {id:33,title:'Array Reduce',category:'JavaScript',difficulty:'Medium',desc:'Implement Array.reduce() from scratch',language:'javascript',testCases:[{input:'[1,2,3,4], (a,b)=>a+b, 0',output:'10'}],hint:'Accumulate values',starter:'function reduce(arr, fn, initial) {\n    // Your code here\n}'},
    {id:34,title:'Debounce Function',category:'JavaScript',difficulty:'Medium',desc:'Implement debounce utility',language:'javascript',testCases:[{input:'Function, 300ms',output:'Delayed execution'}],hint:'Use setTimeout',starter:'function debounce(fn, delay) {\n    // Your code here\n}'},
    {id:35,title:'Throttle Function',category:'JavaScript',difficulty:'Medium',desc:'Implement throttle utility',language:'javascript',testCases:[{input:'Function, 1000ms',output:'Rate limited execution'}],hint:'Track last execution time',starter:'function throttle(fn, limit) {\n    // Your code here\n}'},
    {id:36,title:'Deep Clone',category:'JavaScript',difficulty:'Hard',desc:'Deep clone an object',language:'javascript',testCases:[{input:'{a:1, b:{c:2}}',output:'Independent copy'}],hint:'Handle nested objects',starter:'function deepClone(obj) {\n    // Your code here\n}'},
    {id:37,title:'Flatten Array',category:'JavaScript',difficulty:'Medium',desc:'Flatten nested array',language:'javascript',testCases:[{input:'[1,[2,[3,[4]]]]',output:'[1,2,3,4]'}],hint:'Use recursion',starter:'function flatten(arr) {\n    // Your code here\n}'},
    {id:38,title:'Promise.all',category:'JavaScript',difficulty:'Hard',desc:'Implement Promise.all()',language:'javascript',testCases:[{input:'Array of promises',output:'Resolved array'}],hint:'Track completion',starter:'function promiseAll(promises) {\n    // Your code here\n}'},
    {id:39,title:'Event Emitter',category:'JavaScript',difficulty:'Medium',desc:'Create event emitter class',language:'javascript',testCases:[{input:'on/emit/off methods',output:'Event handling'}],hint:'Use object to store listeners',starter:'class EventEmitter {\n    // Your code here\n}'},
    {id:40,title:'Curry Function',category:'JavaScript',difficulty:'Hard',desc:'Implement function currying',language:'javascript',testCases:[{input:'add(1)(2)(3)',output:'6'}],hint:'Return functions',starter:'function curry(fn) {\n    // Your code here\n}'},
    {id:41,title:'Memoization',category:'JavaScript',difficulty:'Medium',desc:'Implement memoization',language:'javascript',testCases:[{input:'Expensive function',output:'Cached results'}],hint:'Store results in object',starter:'function memoize(fn) {\n    // Your code here\n}'},
    {id:42,title:'Bind Implementation',category:'JavaScript',difficulty:'Hard',desc:'Implement Function.bind()',language:'javascript',testCases:[{input:'Function, context',output:'Bound function'}],hint:'Use apply/call',starter:'Function.prototype.myBind = function(context) {\n    // Your code here\n}'},
    {id:43,title:'Object.assign',category:'JavaScript',difficulty:'Medium',desc:'Implement Object.assign()',language:'javascript',testCases:[{input:'target, sources',output:'Merged object'}],hint:'Copy properties',starter:'function assign(target, ...sources) {\n    // Your code here\n}'},
    {id:44,title:'Array Chunk',category:'JavaScript',difficulty:'Easy',desc:'Split array into chunks',language:'javascript',testCases:[{input:'[1,2,3,4,5], 2',output:'[[1,2],[3,4],[5]]'}],hint:'Use slice',starter:'function chunk(arr, size) {\n    // Your code here\n}'},
    {id:45,title:'String Template',category:'JavaScript',difficulty:'Medium',desc:'Implement template string parser',language:'javascript',testCases:[{input:'"Hello ${name}", {name:"World"}',output:'"Hello World"'}],hint:'Use regex',starter:'function template(str, data) {\n    // Your code here\n}'},
    {id:46,title:'Async Retry',category:'JavaScript',difficulty:'Hard',desc:'Retry async function on failure',language:'javascript',testCases:[{input:'Function, 3 retries',output:'Success or final error'}],hint:'Use recursion with promises',starter:'async function retry(fn, retries) {\n    // Your code here\n}'},
    {id:47,title:'Rate Limiter',category:'JavaScript',difficulty:'Hard',desc:'Implement API rate limiter',language:'javascript',testCases:[{input:'5 requests per second',output:'Queue excess requests'}],hint:'Use queue and timer',starter:'class RateLimiter {\n    // Your code here\n}'},
    {id:48,title:'Virtual DOM Diff',category:'JavaScript',difficulty:'Hard',desc:'Simple virtual DOM diff algorithm',language:'javascript',testCases:[{input:'oldVNode, newVNode',output:'Patch operations'}],hint:'Compare recursively',starter:'function diff(oldNode, newNode) {\n    // Your code here\n}'},
    {id:49,title:'Observable',category:'JavaScript',difficulty:'Hard',desc:'Implement Observable pattern',language:'javascript',testCases:[{input:'subscribe/next/complete',output:'Stream handling'}],hint:'Store observers',starter:'class Observable {\n    // Your code here\n}'},
    {id:50,title:'Lazy Evaluation',category:'JavaScript',difficulty:'Hard',desc:'Implement lazy sequence',language:'javascript',testCases:[{input:'Infinite sequence',output:'Computed on demand'}],hint:'Use generators',starter:'function* lazy(arr) {\n    // Your code here\n}'},
    {id:51,title:'JSON Parser',category:'JavaScript',difficulty:'Hard',desc:'Simple JSON parser',language:'javascript',testCases:[{input:'"{\"a\":1}"',output:'{a:1}'}],hint:'Recursive descent',starter:'function parseJSON(str) {\n    // Your code here\n}'},
    {id:52,title:'Query String Parser',category:'JavaScript',difficulty:'Medium',desc:'Parse URL query string',language:'javascript',testCases:[{input:'"?a=1&b=2"',output:'{a:"1",b:"2"}'}],hint:'Split and parse',starter:'function parseQuery(str) {\n    // Your code here\n}'},
    {id:53,title:'LocalStorage Wrapper',category:'JavaScript',difficulty:'Medium',desc:'Create localStorage wrapper with expiry',language:'javascript',testCases:[{input:'set/get with TTL',output:'Auto-expire items'}],hint:'Store timestamp',starter:'class Storage {\n    // Your code here\n}'},
    {id:54,title:'Intersection Observer',category:'JavaScript',difficulty:'Medium',desc:'Detect element visibility',language:'javascript',testCases:[{input:'Element, callback',output:'Trigger on visible'}],hint:'Use getBoundingClientRect',starter:'function observe(element, callback) {\n    // Your code here\n}'},
    {id:55,title:'Drag and Drop',category:'JavaScript',difficulty:'Hard',desc:'Implement drag and drop',language:'javascript',testCases:[{input:'Draggable elements',output:'Position updates'}],hint:'Mouse events',starter:'function makeDraggable(element) {\n    // Your code here\n}'},
    {id:56,title:'Infinite Scroll',category:'JavaScript',difficulty:'Medium',desc:'Implement infinite scroll',language:'javascript',testCases:[{input:'Container, loadMore',output:'Load on scroll bottom'}],hint:'Check scroll position',starter:'function infiniteScroll(container, loadMore) {\n    // Your code here\n}'},
    {id:57,title:'Form Validator',category:'JavaScript',difficulty:'Medium',desc:'Create form validation library',language:'javascript',testCases:[{input:'Rules, values',output:'Validation errors'}],hint:'Check each rule',starter:'function validate(rules, values) {\n    // Your code here\n}'},
    {id:58,title:'Router',category:'JavaScript',difficulty:'Hard',desc:'Simple client-side router',language:'javascript',testCases:[{input:'Routes, handlers',output:'Navigate between views'}],hint:'Use History API',starter:'class Router {\n    // Your code here\n}'},
    {id:59,title:'State Machine',category:'JavaScript',difficulty:'Hard',desc:'Implement finite state machine',language:'javascript',testCases:[{input:'States, transitions',output:'State management'}],hint:'Track current state',starter:'class StateMachine {\n    // Your code here\n}'},
    {id:60,title:'Web Worker Pool',category:'JavaScript',difficulty:'Hard',desc:'Manage pool of web workers',language:'javascript',testCases:[{input:'Tasks, worker count',output:'Parallel execution'}],hint:'Queue tasks',starter:'class WorkerPool {\n    // Your code here\n}'},
    
    // Data Structures & Algorithms (40)
    {id:61,title:'Stack Implementation',category:'Data Structures',difficulty:'Easy',desc:'Implement stack with push/pop/peek',language:'python',testCases:[{input:'push(1), push(2), pop()',output:'2'}],hint:'Use list',starter:'class Stack:\n    def __init__(self):\n        pass'},
    {id:62,title:'Queue Implementation',category:'Data Structures',difficulty:'Easy',desc:'Implement queue with enqueue/dequeue',language:'python',testCases:[{input:'enqueue(1), enqueue(2), dequeue()',output:'1'}],hint:'Use list or deque',starter:'class Queue:\n    def __init__(self):\n        pass'},
    {id:63,title:'Linked List',category:'Data Structures',difficulty:'Medium',desc:'Implement singly linked list',language:'python',testCases:[{input:'insert, delete, search',output:'List operations'}],hint:'Node class with next pointer',starter:'class LinkedList:\n    def __init__(self):\n        pass'},
    {id:64,title:'Binary Search Tree',category:'Data Structures',difficulty:'Medium',desc:'Implement BST with insert/search/delete',language:'python',testCases:[{input:'insert(5), search(5)',output:'True'}],hint:'Compare with node value',starter:'class BST:\n    def __init__(self):\n        pass'},
    {id:65,title:'Hash Table',category:'Data Structures',difficulty:'Medium',desc:'Implement hash table with chaining',language:'python',testCases:[{input:'put("a",1), get("a")',output:'1'}],hint:'Use list of lists',starter:'class HashTable:\n    def __init__(self):\n        pass'},
    {id:66,title:'Min Heap',category:'Data Structures',difficulty:'Hard',desc:'Implement min heap',language:'python',testCases:[{input:'insert(5), insert(3), extract_min()',output:'3'}],hint:'Use array, heapify',starter:'class MinHeap:\n    def __init__(self):\n        pass'},
    {id:67,title:'Trie',category:'Data Structures',difficulty:'Hard',desc:'Implement trie for word storage',language:'python',testCases:[{input:'insert("cat"), search("cat")',output:'True'}],hint:'Tree of characters',starter:'class Trie:\n    def __init__(self):\n        pass'},
    {id:68,title:'Graph Adjacency List',category:'Data Structures',difficulty:'Medium',desc:'Implement graph with adjacency list',language:'python',testCases:[{input:'add_edge(1,2), neighbors(1)',output:'[2]'}],hint:'Use dictionary of lists',starter:'class Graph:\n    def __init__(self):\n        pass'},
    {id:69,title:'Disjoint Set (Union-Find)',category:'Data Structures',difficulty:'Hard',desc:'Implement union-find data structure',language:'python',testCases:[{input:'union(1,2), find(1)',output:'Same set'}],hint:'Path compression',starter:'class UnionFind:\n    def __init__(self, n):\n        pass'},
    {id:70,title:'Segment Tree',category:'Data Structures',difficulty:'Hard',desc:'Implement segment tree for range queries',language:'python',testCases:[{input:'Range sum query',output:'Sum in O(log n)'}],hint:'Binary tree structure',starter:'class SegmentTree:\n    def __init__(self, arr):\n        pass'},
    {id:71,title:'Quick Sort',category:'Algorithms',difficulty:'Medium',desc:'Implement quicksort algorithm',language:'python',testCases:[{input:'[3,1,4,1,5,9]',output:'[1,1,3,4,5,9]'}],hint:'Partition and recurse',starter:'def quick_sort(arr):\n    # Your code here\n    pass'},
    {id:72,title:'Heap Sort',category:'Algorithms',difficulty:'Medium',desc:'Implement heapsort algorithm',language:'python',testCases:[{input:'[3,1,4,1,5,9]',output:'[1,1,3,4,5,9]'}],hint:'Build heap, extract max',starter:'def heap_sort(arr):\n    # Your code here\n    pass'},
    {id:73,title:'Counting Sort',category:'Algorithms',difficulty:'Medium',desc:'Implement counting sort',language:'python',testCases:[{input:'[4,2,2,8,3,3,1]',output:'[1,2,2,3,3,4,8]'}],hint:'Count occurrences',starter:'def counting_sort(arr):\n    # Your code here\n    pass'},
    {id:74,title:'Radix Sort',category:'Algorithms',difficulty:'Hard',desc:'Implement radix sort',language:'python',testCases:[{input:'[170,45,75,90,802,24,2,66]',output:'Sorted array'}],hint:'Sort by digits',starter:'def radix_sort(arr):\n    # Your code here\n    pass'},
    {id:75,title:'Knapsack Problem',category:'Algorithms',difficulty:'Hard',desc:'0/1 Knapsack using DP',language:'python',testCases:[{input:'weights, values, capacity',output:'Max value'}],hint:'2D DP table',starter:'def knapsack(weights, values, capacity):\n    # Your code here\n    pass'},
    {id:76,title:'Longest Common Subsequence',category:'Algorithms',difficulty:'Hard',desc:'Find LCS of two strings',language:'python',testCases:[{input:'"ABCDGH", "AEDFHR"',output:'3 (ADH)'}],hint:'2D DP',starter:'def lcs(s1, s2):\n    # Your code here\n    pass'},
    {id:77,title:'Edit Distance',category:'Algorithms',difficulty:'Hard',desc:'Minimum edits to convert string',language:'python',testCases:[{input:'"horse", "ros"',output:'3'}],hint:'DP with insert/delete/replace',starter:'def edit_distance(s1, s2):\n    # Your code here\n    pass'},
    {id:78,title:'Matrix Chain Multiplication',category:'Algorithms',difficulty:'Hard',desc:'Optimal matrix multiplication order',language:'python',testCases:[{input:'Matrix dimensions',output:'Min operations'}],hint:'DP with subproblems',starter:'def matrix_chain(dims):\n    # Your code here\n    pass'},
    {id:79,title:'N-Queens',category:'Algorithms',difficulty:'Hard',desc:'Solve N-Queens problem',language:'python',testCases:[{input:'4',output:'2 solutions'}],hint:'Backtracking',starter:'def solve_n_queens(n):\n    # Your code here\n    pass'},
    {id:80,title:'Sudoku Solver',category:'Algorithms',difficulty:'Hard',desc:'Solve Sudoku puzzle',language:'python',testCases:[{input:'9x9 grid',output:'Solved grid'}],hint:'Backtracking',starter:'def solve_sudoku(board):\n    # Your code here\n    pass'},
    {id:81,title:'Topological Sort',category:'Algorithms',difficulty:'Medium',desc:'Topological sort of DAG',language:'python',testCases:[{input:'Graph',output:'Valid ordering'}],hint:'DFS or Kahn\'s algorithm',starter:'def topological_sort(graph):\n    # Your code here\n    pass'},
    {id:82,title:'Kruskal\'s Algorithm',category:'Algorithms',difficulty:'Hard',desc:'Minimum spanning tree',language:'python',testCases:[{input:'Weighted graph',output:'MST edges'}],hint:'Sort edges, union-find',starter:'def kruskal(edges, n):\n    # Your code here\n    pass'},
    {id:83,title:'Prim\'s Algorithm',category:'Algorithms',difficulty:'Hard',desc:'Minimum spanning tree',language:'python',testCases:[{input:'Weighted graph',output:'MST edges'}],hint:'Priority queue',starter:'def prim(graph):\n    # Your code here\n    pass'},
    {id:84,title:'Bellman-Ford',category:'Algorithms',difficulty:'Hard',desc:'Shortest path with negative weights',language:'python',testCases:[{input:'Weighted graph',output:'Shortest distances'}],hint:'Relax edges V-1 times',starter:'def bellman_ford(graph, start):\n    # Your code here\n    pass'},
    {id:85,title:'Floyd-Warshall',category:'Algorithms',difficulty:'Hard',desc:'All pairs shortest path',language:'python',testCases:[{input:'Weighted graph',output:'Distance matrix'}],hint:'3 nested loops',starter:'def floyd_warshall(graph):\n    # Your code here\n    pass'},
    {id:86,title:'Tarjan\'s Algorithm',category:'Algorithms',difficulty:'Hard',desc:'Find strongly connected components',language:'python',testCases:[{input:'Directed graph',output:'SCCs'}],hint:'DFS with low-link values',starter:'def tarjan(graph):\n    # Your code here\n    pass'},
    {id:87,title:'KMP Pattern Matching',category:'Algorithms',difficulty:'Hard',desc:'Knuth-Morris-Pratt algorithm',language:'python',testCases:[{input:'"ABABDABACDABABCABAB", "ABABCABAB"',output:'15'}],hint:'Build LPS array',starter:'def kmp_search(text, pattern):\n    # Your code here\n    pass'},
    {id:88,title:'Rabin-Karp',category:'Algorithms',difficulty:'Medium',desc:'String matching with hashing',language:'python',testCases:[{input:'text, pattern',output:'Match positions'}],hint:'Rolling hash',starter:'def rabin_karp(text, pattern):\n    # Your code here\n    pass'},
    {id:89,title:'Manacher\'s Algorithm',category:'Algorithms',difficulty:'Hard',desc:'Longest palindromic substring',language:'python',testCases:[{input:'"babad"',output:'"bab" or "aba"'}],hint:'Expand around center',starter:'def longest_palindrome(s):\n    # Your code here\n    pass'},
    {id:90,title:'Convex Hull',category:'Algorithms',difficulty:'Hard',desc:'Graham scan for convex hull',language:'python',testCases:[{input:'Points',output:'Hull vertices'}],hint:'Sort by angle',starter:'def convex_hull(points):\n    # Your code here\n    pass'},
    {id:91,title:'Closest Pair of Points',category:'Algorithms',difficulty:'Hard',desc:'Find closest pair in 2D',language:'python',testCases:[{input:'Points',output:'Min distance'}],hint:'Divide and conquer',starter:'def closest_pair(points):\n    # Your code here\n    pass'},
    {id:92,title:'Huffman Coding',category:'Algorithms',difficulty:'Hard',desc:'Build Huffman tree',language:'python',testCases:[{input:'Character frequencies',output:'Encoding tree'}],hint:'Min heap',starter:'def huffman_encoding(freq):\n    # Your code here\n    pass'},
    {id:93,title:'A* Pathfinding',category:'Algorithms',difficulty:'Hard',desc:'A* search algorithm',language:'python',testCases:[{input:'Grid, start, goal',output:'Shortest path'}],hint:'Priority queue with heuristic',starter:'def a_star(grid, start, goal):\n    # Your code here\n    pass'},
    {id:94,title:'Minimax Algorithm',category:'Algorithms',difficulty:'Hard',desc:'Game tree search',language:'python',testCases:[{input:'Game state',output:'Best move'}],hint:'Recursive with alpha-beta',starter:'def minimax(state, depth, maximizing):\n    # Your code here\n    pass'},
    {id:95,title:'Reservoir Sampling',category:'Algorithms',difficulty:'Medium',desc:'Random sampling from stream',language:'python',testCases:[{input:'Stream, k',output:'k random items'}],hint:'Probability-based selection',starter:'def reservoir_sample(stream, k):\n    # Your code here\n    pass'},
    {id:96,title:'Bloom Filter',category:'Algorithms',difficulty:'Hard',desc:'Probabilistic set membership',language:'python',testCases:[{input:'add/contains',output:'Probabilistic results'}],hint:'Multiple hash functions',starter:'class BloomFilter:\n    def __init__(self, size):\n        pass'},
    {id:97,title:'Skip List',category:'Data Structures',difficulty:'Hard',desc:'Probabilistic balanced structure',language:'python',testCases:[{input:'insert/search',output:'O(log n) average'}],hint:'Multiple levels',starter:'class SkipList:\n    def __init__(self):\n        pass'},
    {id:98,title:'B-Tree',category:'Data Structures',difficulty:'Hard',desc:'Self-balancing tree',language:'python',testCases:[{input:'insert/search',output:'Balanced operations'}],hint:'Multiple keys per node',starter:'class BTree:\n    def __init__(self, t):\n        pass'},
    {id:99,title:'Red-Black Tree',category:'Data Structures',difficulty:'Hard',desc:'Self-balancing BST',language:'python',testCases:[{input:'insert/delete',output:'Balanced tree'}],hint:'Color properties',starter:'class RedBlackTree:\n    def __init__(self):\n        pass'},
    {id:100,title:'Suffix Tree',category:'Data Structures',difficulty:'Hard',desc:'Compressed trie of suffixes',language:'python',testCases:[{input:'String',output:'Pattern matching'}],hint:'Ukkonen\'s algorithm',starter:'class SuffixTree:\n    def __init__(self, text):\n        pass'}
  ],
  courses: [
    {
      id:1,
      title:'Python Programming Mastery',
      category:'Programming',
      lessons:10,
      duration:'8 weeks',
      desc:'Complete Python from basics to advanced with real projects',
      topics:['Variables & Data Types','Control Flow','Functions','OOP','File I/O','Modules','Error Handling','Decorators','Generators','Async Programming'],
      content:[
        {lesson:1,title:'Python Basics',videoId:'rfscVS0vtbw',duration:'45:00',quiz:[{q:'What is Python?',options:['Language','Snake','Both'],answer:0}],notes:'Python is a high-level programming language'},
        {lesson:2,title:'Data Types & Variables',videoId:'rfscVS0vtbw',duration:'50:00',quiz:[{q:'Which is mutable?',options:['List','Tuple','String'],answer:0}],notes:'Lists are mutable, tuples are immutable'},
        {lesson:3,title:'Control Flow',videoId:'rfscVS0vtbw',duration:'55:00',quiz:[{q:'What is a loop?',options:['Iteration','Function','Class'],answer:0}],notes:'Loops repeat code blocks'},
        {lesson:4,title:'Functions',videoId:'rfscVS0vtbw',duration:'60:00',quiz:[{q:'What is return?',options:['Output','Input','Loop'],answer:0}],notes:'Functions return values'},
        {lesson:5,title:'Object-Oriented Programming',videoId:'rfscVS0vtbw',duration:'70:00',quiz:[{q:'What is a class?',options:['Blueprint','Object','Function'],answer:0}],notes:'Classes define object structure'},
        {lesson:6,title:'File Handling',videoId:'rfscVS0vtbw',duration:'40:00',quiz:[{q:'How to read file?',options:['open()','read()','file()'],answer:0}],notes:'Use open() to read files'},
        {lesson:7,title:'Modules & Packages',videoId:'rfscVS0vtbw',duration:'45:00',quiz:[{q:'What is import?',options:['Load module','Export','Delete'],answer:0}],notes:'Import brings external code'},
        {lesson:8,title:'Error Handling',videoId:'rfscVS0vtbw',duration:'50:00',quiz:[{q:'What is try-except?',options:['Error handling','Loop','Function'],answer:0}],notes:'Handle errors gracefully'},
        {lesson:9,title:'Advanced Features',videoId:'rfscVS0vtbw',duration:'65:00',quiz:[{q:'What is decorator?',options:['Function wrapper','Class','Loop'],answer:0}],notes:'Decorators modify functions'},
        {lesson:10,title:'Final Project',videoId:'rfscVS0vtbw',duration:'90:00',quiz:[{q:'Ready to build?',options:['Yes','No','Maybe'],answer:0}],notes:'Build a complete application'}
      ]
    },
    {
      id:2,
      title:'Machine Learning Fundamentals',
      category:'AI/ML',
      lessons:10,
      duration:'10 weeks',
      desc:'Learn ML from scratch with hands-on projects',
      topics:['ML Basics','Linear Regression','Logistic Regression','Decision Trees','Random Forest','SVM','Neural Networks','Deep Learning','CNNs','Model Deployment'],
      content:[
        {lesson:1,title:'Introduction to ML',videoId:'jGwO_UgTS7I',duration:'60:00',quiz:[{q:'What is ML?',options:['Learning from data','Magic','Manual coding'],answer:0}],notes:'ML learns patterns from data'},
        {lesson:2,title:'Linear Regression',videoId:'jGwO_UgTS7I',duration:'70:00',quiz:[{q:'What is regression?',options:['Predict numbers','Classify','Cluster'],answer:0}],notes:'Predict continuous values'},
        {lesson:3,title:'Logistic Regression',videoId:'jGwO_UgTS7I',duration:'65:00',quiz:[{q:'What is classification?',options:['Categorize','Predict','Cluster'],answer:0}],notes:'Binary classification'},
        {lesson:4,title:'Decision Trees',videoId:'jGwO_UgTS7I',duration:'55:00',quiz:[{q:'What is tree?',options:['Hierarchical model','Linear','Neural'],answer:0}],notes:'Tree-based decisions'},
        {lesson:5,title:'Ensemble Methods',videoId:'jGwO_UgTS7I',duration:'75:00',quiz:[{q:'What is ensemble?',options:['Multiple models','Single model','No model'],answer:0}],notes:'Combine multiple models'},
        {lesson:6,title:'Support Vector Machines',videoId:'jGwO_UgTS7I',duration:'70:00',quiz:[{q:'What is SVM?',options:['Margin maximizer','Tree','Network'],answer:0}],notes:'Find optimal boundary'},
        {lesson:7,title:'Neural Networks',videoId:'aircAruvnKk',duration:'80:00',quiz:[{q:'What is neuron?',options:['Processing unit','Cell','Function'],answer:0}],notes:'Inspired by brain'},
        {lesson:8,title:'Deep Learning',videoId:'CS4cs9xVecg',duration:'90:00',quiz:[{q:'What is deep?',options:['Many layers','One layer','No layers'],answer:0}],notes:'Multiple hidden layers'},
        {lesson:9,title:'Convolutional Networks',videoId:'CS4cs9xVecg',duration:'85:00',quiz:[{q:'What is CNN?',options:['Image processing','Text','Audio'],answer:0}],notes:'For image data'},
        {lesson:10,title:'Model Deployment',videoId:'jGwO_UgTS7I',duration:'95:00',quiz:[{q:'What is deployment?',options:['Production use','Training','Testing'],answer:0}],notes:'Deploy to production'}
      ]
    },
    {
      id:3,
      title:'Web Development Full Stack',
      category:'Web Development',
      lessons:12,
      duration:'12 weeks',
      desc:'Build modern web applications from frontend to backend',
      topics:['HTML/CSS','JavaScript','React','Node.js','Express','MongoDB','REST APIs','Authentication','Deployment','Testing','Performance','Security'],
      content:[
        {lesson:1,title:'HTML & CSS Basics',videoId:'G3e-cpL7ofc',duration:'60:00',quiz:[{q:'What is HTML?',options:['Markup','Programming','Database'],answer:0}],notes:'Structure web pages'},
        {lesson:2,title:'JavaScript Fundamentals',videoId:'PkZNo7MFNFg',duration:'75:00',quiz:[{q:'What is JS?',options:['Programming language','Markup','Style'],answer:0}],notes:'Add interactivity'},
        {lesson:3,title:'React Basics',videoId:'bMknfKXIFA8',duration:'80:00',quiz:[{q:'What is React?',options:['UI library','Backend','Database'],answer:0}],notes:'Build user interfaces'},
        {lesson:4,title:'React Hooks',videoId:'bMknfKXIFA8',duration:'70:00',quiz:[{q:'What is useState?',options:['State hook','Effect','Ref'],answer:0}],notes:'Manage component state'},
        {lesson:5,title:'Node.js Basics',videoId:'Oe421EPjeBE',duration:'85:00',quiz:[{q:'What is Node?',options:['JS runtime','Framework','Library'],answer:0}],notes:'Server-side JavaScript'},
        {lesson:6,title:'Express Framework',videoId:'Oe421EPjeBE',duration:'75:00',quiz:[{q:'What is Express?',options:['Web framework','Database','Frontend'],answer:0}],notes:'Build web servers'},
        {lesson:7,title:'MongoDB & Mongoose',videoId:'HXV3zeQKqGY',duration:'80:00',quiz:[{q:'What is MongoDB?',options:['NoSQL DB','SQL DB','Cache'],answer:0}],notes:'Document database'},
        {lesson:8,title:'REST API Design',videoId:'Oe421EPjeBE',duration:'70:00',quiz:[{q:'What is REST?',options:['API style','Database','Frontend'],answer:0}],notes:'Stateless API design'},
        {lesson:9,title:'Authentication & Security',videoId:'Oe421EPjeBE',duration:'90:00',quiz:[{q:'What is JWT?',options:['Token','Password','Cookie'],answer:0}],notes:'Secure authentication'},
        {lesson:10,title:'Testing',videoId:'Oe421EPjeBE',duration:'75:00',quiz:[{q:'What is Jest?',options:['Test framework','Library','Database'],answer:0}],notes:'Write unit tests'},
        {lesson:11,title:'Deployment',videoId:'3c-iBn73dDE',duration:'85:00',quiz:[{q:'What is Docker?',options:['Container','VM','Server'],answer:0}],notes:'Containerize apps'},
        {lesson:12,title:'Final Project',videoId:'bMknfKXIFA8',duration:'120:00',quiz:[{q:'Ready to deploy?',options:['Yes','No','Maybe'],answer:0}],notes:'Build full-stack app'}
      ]
    }
  ]
};