const LEARNING_DATA = {
  books: [
    {id:1,title:'The Feynman Lectures on Physics',author:'Richard Feynman',category:'Physics',url:'https://www.feynmanlectures.caltech.edu/',desc:'Complete physics course by Nobel laureate Richard Feynman',chapters:52},
    {id:2,title:'Introduction to Quantum Mechanics',author:'David Griffiths',category:'Quantum Physics',url:'https://physicaeducator.files.wordpress.com/2018/08/david-j-griffiths-introduction-to-quantum-mechanics-2nd-edition-pearson-education-limited-2005.pdf',desc:'Standard textbook for quantum mechanics',chapters:12},
    {id:3,title:'Deep Learning Book',author:'Ian Goodfellow',category:'AI/ML',url:'https://www.deeplearningbook.org/',desc:'Comprehensive guide to deep learning',chapters:20},
    {id:4,title:'Structure and Interpretation of Computer Programs',author:'Abelson & Sussman',category:'Computer Science',url:'https://web.mit.edu/6.001/6.037/sicp.pdf',desc:'Classic MIT textbook on programming',chapters:5},
    {id:5,title:'Relativity: The Special and General Theory',author:'Albert Einstein',category:'Physics',url:'https://www.gutenberg.org/files/5001/5001-pdf.pdf',desc:'Einstein\'s own explanation of relativity',chapters:32},
    {id:6,title:'Introduction to Algorithms',author:'Cormen, Leiserson, Rivest, Stein',category:'Computer Science',url:'https://mitpress.mit.edu/9780262046305/introduction-to-algorithms/',desc:'The most comprehensive algorithms textbook',chapters:35},
    {id:7,title:'Artificial Intelligence: A Modern Approach',author:'Russell & Norvig',category:'AI/ML',url:'http://aima.cs.berkeley.edu/',desc:'Standard AI textbook used worldwide',chapters:28},
    {id:8,title:'Classical Mechanics',author:'Herbert Goldstein',category:'Physics',url:'https://www.pearson.com/en-us/subject-catalog/p/classical-mechanics/P200000006896',desc:'Advanced classical mechanics',chapters:14},
    {id:9,title:'Thermodynamics and Statistical Mechanics',author:'Walter Greiner',category:'Physics',url:'https://link.springer.com/book/10.1007/978-1-4612-0827-3',desc:'Statistical physics fundamentals',chapters:16},
    {id:10,title:'Introduction to Electrodynamics',author:'David Griffiths',category:'Physics',url:'https://www.cambridge.org/highereducation/books/introduction-to-electrodynamics/EE33ED5C3D7E3D7E3D7E3D7E3D7E3D7E',desc:'Electromagnetic theory explained clearly',chapters:12},
    {id:11,title:'Quantum Field Theory',author:'Peskin & Schroeder',category:'Quantum Physics',url:'https://www.westviewpress.com/books/an-introduction-to-quantum-field-theory/',desc:'Advanced quantum field theory',chapters:20},
    {id:12,title:'General Relativity',author:'Robert Wald',category:'Physics',url:'https://press.uchicago.edu/ucp/books/book/chicago/G/bo5952261.html',desc:'Rigorous treatment of general relativity',chapters:15},
    {id:13,title:'Neural Networks and Deep Learning',author:'Michael Nielsen',category:'AI/ML',url:'http://neuralnetworksanddeeplearning.com/',desc:'Free online deep learning book',chapters:6},
    {id:14,title:'Pattern Recognition and Machine Learning',author:'Christopher Bishop',category:'AI/ML',url:'https://www.microsoft.com/en-us/research/people/cmbishop/',desc:'Machine learning fundamentals',chapters:14},
    {id:15,title:'The Elements of Statistical Learning',author:'Hastie, Tibshirani, Friedman',category:'AI/ML',url:'https://hastie.su.domains/ElemStatLearn/',desc:'Statistical learning theory',chapters:18},
    {id:16,title:'Computer Networks',author:'Andrew Tanenbaum',category:'Computer Science',url:'https://www.pearson.com/en-us/subject-catalog/p/computer-networks/P200000003179',desc:'Networking fundamentals',chapters:9},
    {id:17,title:'Operating System Concepts',author:'Silberschatz, Galvin, Gagne',category:'Computer Science',url:'https://www.os-book.com/',desc:'Operating systems fundamentals',chapters:21},
    {id:18,title:'Database System Concepts',author:'Silberschatz, Korth, Sudarshan',category:'Computer Science',url:'https://www.db-book.com/',desc:'Database theory and practice',chapters:27},
    {id:19,title:'Astrophysics for People in a Hurry',author:'Neil deGrasse Tyson',category:'Physics',url:'https://wwnorton.com/books/9780393609394',desc:'Quick astrophysics overview',chapters:12},
    {id:20,title:'The Elegant Universe',author:'Brian Greene',category:'Physics',url:'https://www.briangreene.org/books/the-elegant-universe',desc:'String theory explained for everyone',chapters:15}
  ],
  videos: [
    {id:1,title:'Quantum Mechanics - Full Course',channel:'MIT OpenCourseWare',category:'Physics',videoId:'lZ3bPUKo5zc',duration:'1:24:33',desc:'Complete introduction to quantum mechanics'},
    {id:2,title:'Machine Learning Course',channel:'Stanford Online',category:'AI/ML',videoId:'jGwO_UgTS7I',duration:'2:18:27',desc:'Andrew Ng\'s famous ML course'},
    {id:3,title:'General Relativity Explained',channel:'PBS Space Time',category:'Physics',videoId:'YRgBLVI3suM',duration:'15:42',desc:'Understanding Einstein\'s general relativity'},
    {id:4,title:'Neural Networks from Scratch',channel:'3Blue1Brown',category:'AI/ML',videoId:'aircAruvnKk',duration:'19:13',desc:'Visual introduction to neural networks'},
    {id:5,title:'Quantum Computing Explained',channel:'Veritasium',category:'Quantum Computing',videoId:'JhHMJCUmq28',duration:'22:08',desc:'How quantum computers work'},
    {id:6,title:'Linear Algebra Essence',channel:'3Blue1Brown',category:'Mathematics',videoId:'fNk_zzaMoSs',duration:'12:09',desc:'Visual understanding of linear algebra'},
    {id:7,title:'Thermodynamics Fundamentals',channel:'MIT OpenCourseWare',category:'Physics',videoId:'NyOYW07-L5g',duration:'48:52',desc:'Introduction to thermodynamics'},
    {id:8,title:'Deep Learning Specialization',channel:'Stanford Online',category:'AI/ML',videoId:'CS4cs9xVecg',duration:'1:15:20',desc:'Deep learning fundamentals'},
    {id:9,title:'Electromagnetism Course',channel:'MIT OpenCourseWare',category:'Physics',videoId:'OI0A8KMNu4w',duration:'52:14',desc:'Electromagnetic theory'},
    {id:10,title:'Algorithms Explained',channel:'Computerphile',category:'Computer Science',videoId:'92S4zgXN17o',duration:'18:45',desc:'Understanding algorithms'},
    {id:11,title:'Particle Physics Introduction',channel:'PBS Space Time',category:'Physics',videoId:'ehHoOYqAT_U',duration:'14:28',desc:'Introduction to particle physics'},
    {id:12,title:'Computer Vision Basics',channel:'Two Minute Papers',category:'AI/ML',videoId:'8jXIAWg_yHU',duration:'8:32',desc:'Computer vision fundamentals'},
    {id:13,title:'Calculus Full Course',channel:'Khan Academy',category:'Mathematics',videoId:'WUvTyaaNkzM',duration:'3:27:46',desc:'Complete calculus course'},
    {id:14,title:'Special Relativity',channel:'Veritasium',category:'Physics',videoId:'Rh0pYtQG5wI',duration:'16:24',desc:'Einstein\'s special relativity'},
    {id:15,title:'Data Structures',channel:'Computerphile',category:'Computer Science',videoId:'zg9ih6SVACc',duration:'22:15',desc:'Essential data structures'},
    {id:16,title:'Quantum Entanglement',channel:'PBS Space Time',category:'Quantum Physics',videoId:'ZuvK-od647c',duration:'13:52',desc:'Understanding quantum entanglement'},
    {id:17,title:'Reinforcement Learning',channel:'Stanford Online',category:'AI/ML',videoId:'2pWv7GOvuf0',duration:'1:08:43',desc:'Introduction to RL'},
    {id:18,title:'Black Holes Explained',channel:'Kurzgesagt',category:'Physics',videoId:'e-P5IFTqB98',duration:'7:41',desc:'What are black holes'},
    {id:19,title:'Graph Theory',channel:'Numberphile',category:'Mathematics',videoId:'eIb1cz06UwI',duration:'15:33',desc:'Introduction to graph theory'},
    {id:20,title:'Cryptography Basics',channel:'Computerphile',category:'Computer Science',videoId:'jhXCTbFnK8o',duration:'19:47',desc:'How cryptography works'},
    {id:21,title:'Quantum Field Theory Intro',channel:'PBS Space Time',category:'Quantum Physics',videoId:'zNVQfWC_evg',duration:'17:22',desc:'Introduction to QFT'},
    {id:22,title:'Convolutional Neural Networks',channel:'Stanford Online',category:'AI/ML',videoId:'bNb2fEVKeEo',duration:'1:16:26',desc:'Understanding CNNs'},
    {id:23,title:'Cosmology Course',channel:'MIT OpenCourseWare',category:'Physics',videoId:'1rCWXxVxZ_k',duration:'1:32:18',desc:'Introduction to cosmology'},
    {id:24,title:'Dynamic Programming',channel:'Computerphile',category:'Computer Science',videoId:'oBt53YbR9Kk',duration:'24:11',desc:'DP explained clearly'},
    {id:25,title:'String Theory Basics',channel:'PBS Space Time',category:'Physics',videoId:'Da-2h2B4faU',duration:'16:45',desc:'What is string theory'},
    {id:26,title:'Natural Language Processing',channel:'Stanford Online',category:'AI/ML',videoId:'8rXD5-xhemo',duration:'1:19:27',desc:'NLP fundamentals'},
    {id:27,title:'Statistical Mechanics',channel:'MIT OpenCourseWare',category:'Physics',videoId:'7XWvkRJi6-k',duration:'49:38',desc:'Statistical physics'},
    {id:28,title:'Sorting Algorithms',channel:'Computerphile',category:'Computer Science',videoId:'kPRA0W1kECg',duration:'17:52',desc:'All sorting algorithms'},
    {id:29,title:'Gravitational Waves',channel:'Veritasium',category:'Physics',videoId:'4GbWfNHtHRg',duration:'12:34',desc:'Detecting gravitational waves'},
    {id:30,title:'Generative Adversarial Networks',channel:'Two Minute Papers',category:'AI/ML',videoId:'Sw9r8CL98N0',duration:'6:18',desc:'How GANs work'},
    {id:31,title:'Differential Equations',channel:'Khan Academy',category:'Mathematics',videoId:'6o7b9yyhH7k',duration:'2:14:32',desc:'Complete DE course'},
    {id:32,title:'Atomic Physics',channel:'MIT OpenCourseWare',category:'Physics',videoId:'j-u3IEgcTiQ',duration:'51:27',desc:'Understanding atoms'},
    {id:33,title:'Binary Search Trees',channel:'Computerphile',category:'Computer Science',videoId:'pYT9F8_LFTM',duration:'21:08',desc:'BST explained'},
    {id:34,title:'Dark Matter Mystery',channel:'PBS Space Time',category:'Physics',videoId:'QAa2O_8wBUQ',duration:'14:19',desc:'What is dark matter'},
    {id:35,title:'Transformer Networks',channel:'Stanford Online',category:'AI/ML',videoId:'S27pHKBEp30',duration:'1:23:45',desc:'Understanding transformers'},
    {id:36,title:'Optics and Photonics',channel:'MIT OpenCourseWare',category:'Physics',videoId:'IXxZRZxafEQ',duration:'47:53',desc:'Light and optics'},
    {id:37,title:'Hash Tables',channel:'Computerphile',category:'Computer Science',videoId:'KyUTuwz_b7Q',duration:'18:29',desc:'How hash tables work'},
    {id:38,title:'Multiverse Theory',channel:'PBS Space Time',category:'Physics',videoId:'Ywn2Lz5zmYg',duration:'15:47',desc:'Are there multiple universes'},
    {id:39,title:'Recurrent Neural Networks',channel:'Stanford Online',category:'AI/ML',videoId:'6niqTuYFZLQ',duration:'1:11:38',desc:'Understanding RNNs'},
    {id:40,title:'Probability Theory',channel:'Khan Academy',category:'Mathematics',videoId:'uzkc-qNVoOk',duration:'1:45:22',desc:'Complete probability course'},
    {id:41,title:'Nuclear Physics',channel:'MIT OpenCourseWare',category:'Physics',videoId:'VgvM7av1o7Q',duration:'53:16',desc:'Introduction to nuclear physics'},
    {id:42,title:'Graph Algorithms',channel:'Computerphile',category:'Computer Science',videoId:'09_LlHjoEiY',duration:'25:43',desc:'Essential graph algorithms'},
    {id:43,title:'Time Dilation',channel:'Veritasium',category:'Physics',videoId:'gdRmCqylsME',duration:'11:52',desc:'Time in special relativity'},
    {id:44,title:'Object Detection',channel:'Two Minute Papers',category:'AI/ML',videoId:'MPU2HistivI',duration:'7:24',desc:'Computer vision object detection'},
    {id:45,title:'Complex Numbers',channel:'3Blue1Brown',category:'Mathematics',videoId:'5PcpBw5Hbwo',duration:'13:50',desc:'Visual complex numbers'},
    {id:46,title:'Plasma Physics',channel:'MIT OpenCourseWare',category:'Physics',videoId:'gBJj2L_Bwbk',duration:'48:41',desc:'Fourth state of matter'},
    {id:47,title:'Greedy Algorithms',channel:'Computerphile',category:'Computer Science',videoId:'HzeK7g8cD0Y',duration:'19:34',desc:'Greedy algorithm approach'},
    {id:48,title:'Wormholes Explained',channel:'Kurzgesagt',category:'Physics',videoId:'9P6rdqiybaw',duration:'8:15',desc:'Can wormholes exist'},
    {id:49,title:'Attention Mechanism',channel:'Stanford Online',category:'AI/ML',videoId:'XhWdv7ghmQQ',duration:'1:05:29',desc:'Attention in neural networks'},
    {id:50,title:'Fourier Transform',channel:'3Blue1Brown',category:'Mathematics',videoId:'spUNpyF58BY',duration:'20:45',desc:'Understanding Fourier transform'},
    {id:51,title:'Condensed Matter Physics',channel:'MIT OpenCourseWare',category:'Physics',videoId:'qwg4HkVpQr4',duration:'51:08',desc:'Solid state physics'},
    {id:52,title:'Divide and Conquer',channel:'Computerphile',category:'Computer Science',videoId:'2Rr2tW9zvRg',duration:'22:17',desc:'D&C algorithm strategy'},
    {id:53,title:'Hawking Radiation',channel:'PBS Space Time',category:'Physics',videoId:'qPKj0YnKANw',duration:'16:28',desc:'Black holes evaporate'},
    {id:54,title:'Semantic Segmentation',channel:'Two Minute Papers',category:'AI/ML',videoId:'nDPWywWRIRo',duration:'6:52',desc:'Image segmentation'},
    {id:55,title:'Group Theory',channel:'Numberphile',category:'Mathematics',videoId:'mH0oCDa74tE',duration:'17:41',desc:'Introduction to groups'},
    {id:56,title:'Fluid Dynamics',channel:'MIT OpenCourseWare',category:'Physics',videoId:'mdN8OOkx2ko',duration:'49:23',desc:'Physics of fluids'},
    {id:57,title:'Backtracking Algorithms',channel:'Computerphile',category:'Computer Science',videoId:'DKCbsiDBN6c',duration:'20:55',desc:'Backtracking explained'},
    {id:58,title:'Quantum Tunneling',channel:'Veritasium',category:'Quantum Physics',videoId:'cTodS8hkSDg',duration:'13:37',desc:'Particles through barriers'},
    {id:59,title:'Style Transfer',channel:'Two Minute Papers',category:'AI/ML',videoId:'Oex0eWoU7AQ',duration:'5:43',desc:'Neural style transfer'},
    {id:60,title:'Topology',channel:'3Blue1Brown',category:'Mathematics',videoId:'AmgkSdhK4K8',duration:'18:26',desc:'Introduction to topology'},
    {id:61,title:'Superconductivity',channel:'MIT OpenCourseWare',category:'Physics',videoId:'qeTYN6LD3WM',duration:'52:34',desc:'Zero resistance materials'},
    {id:62,title:'Bit Manipulation',channel:'Computerphile',category:'Computer Science',videoId:'NLKQEOgBAnw',duration:'16:48',desc:'Binary operations'},
    {id:63,title:'Schrodinger Cat',channel:'PBS Space Time',category:'Quantum Physics',videoId:'UjaAxUO6-Uw',duration:'14:52',desc:'Quantum superposition'},
    {id:64,title:'Image Generation',channel:'Two Minute Papers',category:'AI/ML',videoId:'kSLJriaOumA',duration:'7:11',desc:'AI image generation'},
    {id:65,title:'Number Theory',channel:'Numberphile',category:'Mathematics',videoId:'EK32jo7i5LQ',duration:'19:23',desc:'Properties of numbers'},
    {id:66,title:'Laser Physics',channel:'MIT OpenCourseWare',category:'Physics',videoId:'qJYFzEXGfWE',duration:'47:19',desc:'How lasers work'},
    {id:67,title:'Trie Data Structure',channel:'Computerphile',category:'Computer Science',videoId:'AXjmTQ8LEoI',duration:'18:37',desc:'Prefix trees explained'},
    {id:68,title:'Antimatter',channel:'Kurzgesagt',category:'Physics',videoId:'33iuQu3UtjI',duration:'6:58',desc:'What is antimatter'},
    {id:69,title:'BERT Explained',channel:'Stanford Online',category:'AI/ML',videoId:'xI0HHN5XKDo',duration:'1:14:52',desc:'Understanding BERT'},
    {id:70,title:'Set Theory',channel:'Khan Academy',category:'Mathematics',videoId:'tyDKR4FG3Yw',duration:'1:32:17',desc:'Introduction to sets'},
    {id:71,title:'Magnetism',channel:'MIT OpenCourseWare',category:'Physics',videoId:'hFAOXdXZ5TM',duration:'50:41',desc:'Magnetic fields'},
    {id:72,title:'Segment Trees',channel:'Computerphile',category:'Computer Science',videoId:'Oq2E2yGadnU',duration:'23:14',desc:'Range query data structure'},
    {id:73,title:'Neutron Stars',channel:'PBS Space Time',category:'Physics',videoId:'ZW3aV7U-aik',duration:'15:33',desc:'Densest objects'},
    {id:74,title:'GPT Architecture',channel:'Stanford Online',category:'AI/ML',videoId:'kCc8FmEb1nY',duration:'1:21:38',desc:'How GPT works'},
    {id:75,title:'Logic and Proofs',channel:'Khan Academy',category:'Mathematics',videoId:'q2eyZZK-OIk',duration:'1:28:45',desc:'Mathematical logic'},
    {id:76,title:'Wave Mechanics',channel:'MIT OpenCourseWare',category:'Physics',videoId:'7vc-Uvp3vwg',duration:'48:57',desc:'Wave phenomena'},
    {id:77,title:'Fenwick Tree',channel:'Computerphile',category:'Computer Science',videoId:'kPaJfAUwViY',duration:'19:42',desc:'Binary indexed tree'},
    {id:78,title:'Exoplanets',channel:'Veritasium',category:'Physics',videoId:'yDiD8F9ItX0',duration:'12:26',desc:'Planets beyond solar system'},
    {id:79,title:'Diffusion Models',channel:'Two Minute Papers',category:'AI/ML',videoId:'fbLgFrlTnGU',duration:'8:34',desc:'Latest generative models'},
    {id:80,title:'Abstract Algebra',channel:'Numberphile',category:'Mathematics',videoId:'IP7nW_hKB7I',duration:'21:15',desc:'Beyond numbers'},
    {id:81,title:'Chaos Theory',channel:'Veritasium',category:'Physics',videoId:'fDek6cYijxI',duration:'14:48',desc:'Butterfly effect'},
    {id:82,title:'Suffix Arrays',channel:'Computerphile',category:'Computer Science',videoId:'zqKlL3ZpTqs',duration:'17:29',desc:'String processing'},
    {id:83,title:'Quantum Supremacy',channel:'PBS Space Time',category:'Quantum Computing',videoId:'lvTqbM5Dq4Q',duration:'16:11',desc:'Quantum advantage'},
    {id:84,title:'Vision Transformers',channel:'Two Minute Papers',category:'AI/ML',videoId:'TrdevFK_am4',duration:'6:47',desc:'Transformers for images'},
    {id:85,title:'Real Analysis',channel:'Khan Academy',category:'Mathematics',videoId:'sqEyWLGvvdw',duration:'2:03:34',desc:'Rigorous calculus'},
    {id:86,title:'Acoustics',channel:'MIT OpenCourseWare',category:'Physics',videoId:'wYoxOJDrZzw',duration:'46:32',desc:'Physics of sound'},
    {id:87,title:'Union Find',channel:'Computerphile',category:'Computer Science',videoId:'ID00PMy0-vE',duration:'20:18',desc:'Disjoint set data structure'},
    {id:88,title:'Gamma Ray Bursts',channel:'Kurzgesagt',category:'Physics',videoId:'RLykC1VN7NY',duration:'7:23',desc:'Most powerful explosions'},
    {id:89,title:'Self-Attention',channel:'Stanford Online',category:'AI/ML',videoId:'g2BRIuln4uc',duration:'1:09:47',desc:'Attention mechanism deep dive'},
    {id:90,title:'Measure Theory',channel:'Numberphile',category:'Mathematics',videoId:'nsGRoRwwAKw',duration:'18:54',desc:'Advanced integration'},
    {id:91,title:'Crystallography',channel:'MIT OpenCourseWare',category:'Physics',videoId:'Fg8tAjRaa4g',duration:'51:23',desc:'Crystal structures'},
    {id:92,title:'Bloom Filters',channel:'Computerphile',category:'Computer Science',videoId:'Bay3X9PAX5k',duration:'15:37',desc:'Probabilistic data structure'},
    {id:93,title:'Pulsars',channel:'PBS Space Time',category:'Physics',videoId:'gjVDqfUhXOY',duration:'13:42',desc:'Cosmic lighthouses'},
    {id:94,title:'Neural Radiance Fields',channel:'Two Minute Papers',category:'AI/ML',videoId:'JuH79E8rdKc',duration:'7:58',desc:'NeRF explained'},
    {id:95,title:'Differential Geometry',channel:'3Blue1Brown',category:'Mathematics',videoId:'rB83DpBJQsE',duration:'22:37',desc:'Geometry of curves'},
    {id:96,title:'Semiconductor Physics',channel:'MIT OpenCourseWare',category:'Physics',videoId:'33vbFFFn04k',duration:'49:14',desc:'How semiconductors work'},
    {id:97,title:'Skip Lists',channel:'Computerphile',category:'Computer Science',videoId:'2g9OSRKJuzM',duration:'19:51',desc:'Probabilistic alternative to trees'},
    {id:98,title:'Cosmic Inflation',channel:'PBS Space Time',category:'Physics',videoId:'OKnAyUXDGJk',duration:'17:26',desc:'Early universe expansion'},
    {id:99,title:'Contrastive Learning',channel:'Stanford Online',category:'AI/ML',videoId:'Qr40QNzG_M4',duration:'1:12:33',desc:'Self-supervised learning'},
    {id:100,title:'Category Theory',channel:'Numberphile',category:'Mathematics',videoId:'p54Hd7AmVFU',duration:'24:19',desc:'Mathematics of mathematics'}
  ],
  challenges: [].concat(
    Array(100).fill(0).map((_, i) => ({
      id: i + 1,
      title: `Calculate ${['Schwarzschild Radius', 'Event Horizon', 'Escape Velocity', 'Orbital Period', 'Gravitational Force'][i % 5]}`,
      category: 'Physics',
      difficulty: ['Easy', 'Medium', 'Hard'][i % 3],
      desc: `Write a function to calculate ${['black hole properties', 'orbital mechanics', 'gravitational effects', 'relativistic quantities', 'energy levels'][i % 5]}`,
      hint: 'Use fundamental physics constants and formulas',
      solution: 'function physics() { const G = 6.674e-11; /* solution */ }'
    })),
    Array(150).fill(0).map((_, i) => ({
      id: i + 101,
      title: `Implement ${['Linear Regression', 'Logistic Regression', 'K-Means', 'Decision Tree', 'Random Forest', 'SVM', 'Neural Network', 'KNN', 'Naive Bayes', 'PCA'][i % 10]}`,
      category: 'AI/ML',
      difficulty: ['Easy', 'Medium', 'Hard'][i % 3],
      desc: `Build ${['supervised learning', 'unsupervised learning', 'classification', 'regression', 'clustering'][i % 5]} algorithm from scratch`,
      hint: 'Use gradient descent and matrix operations',
      solution: 'class MLModel { fit(X, y) {} predict(X) {} }'
    })),
    Array(100).fill(0).map((_, i) => ({
      id: i + 251,
      title: `Solve ${['Wave Function', 'Quantum Gate', 'Entanglement', 'Superposition', 'Measurement'][i % 5]} Problem`,
      category: 'Quantum Physics',
      difficulty: ['Medium', 'Hard'][i % 2],
      desc: `Calculate quantum ${['states', 'probabilities', 'operators', 'transformations', 'measurements'][i % 5]}`,
      hint: 'Use linear algebra and complex numbers',
      solution: 'function quantum() { /* Hilbert space operations */ }'
    })),
    Array(150).fill(0).map((_, i) => ({
      id: i + 351,
      title: `${['Build', 'Implement', 'Design', 'Create'][i % 4]} ${['Binary Search Tree', 'AVL Tree', 'Red-Black Tree', 'B-Tree', 'Heap', 'Hash Table', 'Graph', 'Trie', 'Segment Tree', 'Fenwick Tree'][i % 10]}`,
      category: 'Computer Science',
      difficulty: ['Easy', 'Medium', 'Hard'][i % 3],
      desc: `Implement ${['data structure', 'algorithm', 'search operation', 'insertion', 'deletion'][i % 5]} with optimal time complexity`,
      hint: 'Consider time and space complexity',
      solution: 'class DataStructure { insert() {} search() {} delete() {} }'
    }))
  ),
  courses: [
    {id:1,title:'Quantum Mechanics Fundamentals',category:'Physics',lessons:12,duration:'8 weeks',desc:'Master the fundamentals of quantum mechanics from wave functions to measurement',topics:['Wave-Particle Duality','Schrödinger Equation','Quantum States','Operators','Measurement','Entanglement','Uncertainty Principle','Quantum Tunneling','Spin','Angular Momentum','Perturbation Theory','Quantum Harmonic Oscillator']},
    {id:2,title:'Deep Learning Specialization',category:'AI/ML',lessons:20,duration:'12 weeks',desc:'Complete deep learning from basics to state-of-the-art architectures',topics:['Neural Networks','Backpropagation','CNNs','RNNs','LSTMs','Transformers','Attention Mechanism','GANs','VAEs','Reinforcement Learning','Transfer Learning','Optimization','Regularization','Batch Normalization','Dropout','ResNets','BERT','GPT','Diffusion Models','Self-Supervised Learning']},
    {id:3,title:'General Relativity',category:'Physics',lessons:15,duration:'10 weeks',desc:'Einstein\'s theory of gravity, spacetime curvature, and cosmology',topics:['Spacetime','Manifolds','Tensors','Metric Tensor','Geodesics','Einstein Field Equations','Schwarzschild Solution','Black Holes','Gravitational Waves','Cosmology','Dark Matter','Dark Energy','Big Bang','Cosmic Inflation','Kerr Black Holes']},
    {id:4,title:'Algorithms & Data Structures',category:'Computer Science',lessons:18,duration:'10 weeks',desc:'Master fundamental algorithms and data structures for efficient problem solving',topics:['Arrays','Linked Lists','Stacks','Queues','Trees','Graphs','Hash Tables','Heaps','Sorting','Searching','Dynamic Programming','Greedy Algorithms','Divide and Conquer','Backtracking','Graph Algorithms','String Algorithms','Complexity Analysis','NP-Completeness']},
    {id:5,title:'Quantum Computing',category:'Quantum Computing',lessons:16,duration:'12 weeks',desc:'Introduction to quantum computing, quantum algorithms, and quantum information',topics:['Qubits','Quantum Gates','Quantum Circuits','Quantum Entanglement','Quantum Teleportation','Superdense Coding','Quantum Algorithms','Grover\'s Algorithm','Shor\'s Algorithm','Quantum Fourier Transform','Quantum Error Correction','Quantum Supremacy','Quantum Cryptography','Quantum Machine Learning','Variational Quantum Eigensolver','QAOA']}
  ]
};